#!/bin/bash

ARC=../../arc/arc

$ARC e ACCOLADE.ARC
$ARC e COUNTA.ARC
$ARC e COUNTASB.ARC
$ARC e GAS.ARC
$ARC e LLOGO.ARC
$ARC e LOTUS.ARC
$ARC e LOTUSSB.ARC
$ARC e P911T.ARC
$ARC e P911TSB.ARC
$ARC e ROSSA.ARC
$ARC e ROSSASB.ARC
$ARC e SLOGO.ARC
$ARC e TESTDRV.ARC
$ARC e VETTE.ARC
$ARC e VETTESB.ARC
$ARC e XROADA.ARC
$ARC e XROADB.ARC
$ARC e XROADC.ARC
